### ISSUE TITLE
Make a zip file of all the Excel files

### ISSUE THREAD

**Issue by markbrough** [iati-data-access/data-backend#16]
**Background**
Currently, it's not possible to download all the XLSX files. Previously, when the files were hosted on Github Pages, it was possible to do so (because Github makes it possible to download a branch as a zip file).

**Requirements**
It would be great to add this functionality back in again - it's useful if people are trying to do analysis across all countries.

I think this should be one zip file per language.

Perhaps it would be good to do the same for the CSV files as well? These can be 

Pinging @sarahshamiso in case I have missed anything here.

**Comment by sarahshamiso** [comment]
Looks good! Thanks, @markbrough. 

I would just add that there are queries in the [Data User Query Corner](https://iaticonnect.org/Data-Use-Query-Corner) that use these batch downloads and even though we have the Custom Data Download, this may be the best option in some use cases, so good to restore it and then update these links / share with the community where they can find them again. 

@codywallace may have something to add here as he updated the queries most recently, but just generally a good option to have available.

**Comment by simon-20** [comment]
This has now been completed.
