### ISSUE TITLE
Data exports cannot be downloaded from CDFD

### ISSUE THREAD

**Issue by IsabelBirds** [iati-data-access/data-backend#21]
On both the dashboards and custom data downloads, the xlsx download does not work and creates the following error message.

![image](https://github.com/iati-data-access/data-backend/assets/44876111/82578e65-6f0b-4c23-856d-19ba3a1d34ed)

**Comment by markbrough** [comment]
@IsabelBirds please could you add the URL of the page, and also add the URL of the Excel file it's trying to download? I just tried this on the following page and it seems to work for me:

https://countrydata.iatistandard.org/data/

**Comment by markbrough** [comment]
Hmm it appears to be a CORS issue that occurs in Firefox!
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://cdfd.iati.opendataservices.coop/api/babbage/cubes/iatiline/aggregate/?drilldown=recipient_country_or_region&order=value_usd.sum:desc&cut=year:%222022%22&aggregates=value_usd.sum&rollup=transaction_type.code:[[%22budget%22],[%223%22,%224%22]]&pagesize=1048576&format=xlsx&lang=en. (Reason: CORS preflight response did not succeed). Status code: 500.
```
